### ISSUE TITLE
Tests fail with Pillow 4.2+

### ISSUE THREAD

**Issue by QuLogic** [openpaperwork/libpillowfight#9]
With Pillow 4.3, tests fail [writing JPEGs with alpha channel](https://kojipkgs.fedoraproject.org//work/tasks/8921/23918921/build.log). I believe this is due to python-pillow/Pillow#2609 which is in 4.2+

**Comment by jflesch** [comment]
Thanks for reporting this issue :)
Fix: e57538207a4294171712d92d703818bf5a227fe0
